In [34]:
import numpy as np
import sys
#importing required packages/libaries

In [5]:
a = np.zeros(3) #creates a numpy array populated with 0's
    #the 0's are floats
a

numpy.float64

In [6]:
z = np.zeros(10) #creates a slightly larger array
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
z.shape = (10,1) #changes the shape of z (10 rows, 1 column)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
z = np.ones(10) #populates array with 1
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
z = np.empty(3) #creates an empty array
z

array([0., 0., 0.])

In [11]:
z = np.linspace(2, 10, 5) #from 2 to 10 with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
z = np.array([10,20]) #ndarray from Python list
z

array([10, 20])

In [13]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list]) #creates array from a_list object
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [14]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]
z = np.array([b_list])
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [15]:
z.shape

(1, 2, 7)

In [ ]:
#type z."TAB" to see all available functions to use

In [16]:
?z #gives more info about the z object

In [17]:
np.random.seed(0)
z1 = np.random.randint(10,size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [18]:
z1[0] #grabs the first element of the array

5

In [19]:
z1[0:2] #gives us a range of elements

array([5, 0])

In [20]:
z1[-1] #gives us the last element

9

In [21]:
z = np.array([1,2,3,4,5])

In [22]:
z < 3 #outputs true/false array

array([ True,  True, False, False, False])

In [23]:
z > 3 #outputs true/false array

array([False, False, False,  True,  True])

In [24]:
z[z > 3] #gives the array where the array is greater than 3

array([4, 5])

In [25]:
a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

In [26]:
a_array + b_array #adds each element of the arrays together

array([ 7,  9, 11, 13, 15])

In [27]:
a_array + 30 #adds 30 to each element of the array

array([31, 32, 33, 34, 35])

In [28]:
a_array * b_array #multiplies together the corresponding elements
                    #of the arrays

array([ 6, 14, 24, 36, 50])

In [29]:
a_array * 10 #multiplies each element of the array by 10

array([10, 20, 30, 40, 50])

In [30]:
a_array @ b_array #gives us the dot product of the two arrays

130

In [33]:
x = np.array([2,1,4,3,5])
np.sort(x) #sorts the array in order

array([1, 2, 3, 4, 5])

# MORE THOROUGH TUTORIAL BEGINS BELOW (2nd video)

## The Basics

In [36]:
a = np.array([1,2,3]) #1D array containing 1,2,3
print(a)

[1 2 3]


In [38]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [39]:
# Get Dimension
a.ndim

1

In [40]:
# Get Shape
b.shape #(rows, columns)

(2, 3)

In [42]:
# Get Type
a.dtype

dtype('int64')

In [43]:
# Get Size
a.itemsize

8

In [44]:
# Get Size (2)
a.size #total # of elements

3

In [45]:
# Get Total Size
b.nbytes

48

## Accessing/Changing specific elements, rows, columns, etc.

In [46]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [48]:
a.shape #shows that a is a 2 x 7

(2, 7)

In [49]:
# Get a specific element [r,c]
a[1,5] #remember Python indexing starts at 0

13

In [51]:
# Get a specific row
a[0, :] #give us everything in the first row

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
# Get a specific column
a[:, 2] #give us everything in the third column

array([ 3, 10])

In [53]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [54]:
a[1,5] = 20 #changes an element
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [55]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [58]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
# Get specific element (work outside in)
b[0,1,1] #gives us the 4

4

In [61]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [63]:
# ALL 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# ALL 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [66]:
# Any other number
np.full((2,2), 99) #shape, value(s)

array([[99, 99],
       [99, 99]])

In [67]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [68]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.6235637 , 0.38438171],
       [0.29753461, 0.05671298],
       [0.27265629, 0.47766512],
       [0.81216873, 0.47997717]])

In [70]:
# Random integer values
np.random.randint(7,size=(3,3)) #value range (0-7), size of array

array([[5, 1, 5],
       [0, 1, 4],
       [3, 0, 3]])

In [71]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [81]:
# Test
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:4,1:4] = z
print(output) #gives us what we want!

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!

In [86]:
a = np.array([1,2,3])
# b = a
b = a.copy()
b[0] = 100

print(a)
print(b)
#both will be the same if we do b = a
#need to use .copy() to prevent that

[1 2 3]
[100   2   3]


## Mathematics

In [88]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [89]:
a + 2

array([3, 4, 5, 6])

In [91]:
a - 2

array([-1,  0,  1,  2])

In [92]:
a * 2

array([2, 4, 6, 8])

In [93]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [95]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [96]:
a ** 2 # a^2

array([ 1,  4,  9, 16])

In [97]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [98]:
# Take the cos
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

##### Linear Algebra

In [102]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b) # multiplies a and b -> matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [104]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [105]:
## Reference docs(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

##### Statistics

In [106]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# Find the min
np.min(stats)

1

In [108]:
# Find the max
np.max(stats)

6

In [109]:
# Find the sum
np.sum(stats)

21

## Reorganizing Arrays

In [114]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2)) # just needs to have the same
                                 # amount of values
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [116]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

##### Load Data from File

In [122]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32') #makes a copy
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [123]:
filedata > 50 #true/false response

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [124]:
filedata[filedata > 50] #only returns the values greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [125]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [126]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [128]:
(filedata > 50) & (filedata < 100) #must have parentheses

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [129]:
(~(filedata > 50) & (filedata < 100)) # '~' means not

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])